Repository mapbox/mapbox-plugins-android, pull requests merged in 2018-05, with the labels that each got.

#471 Test written to try and reproduce issue 470
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/IsolatedActivityPluginTest.kt
  app/src/androidTest/java/com/mapbox/mapboxsdk/utils/OnMapFragmentReadyIdlingResource.kt
  app/src/androidTest/java/com/mapbox/mapboxsdk/utils/WaitLoopAction.java
Labels: ready for review

#475 fixes some issues with Samsung phones throwing exception on rotation vector
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/CompassManager.java
Labels: ready for review

#476 Only adds location source once the first location update occurs
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/IsolatedActivityPluginTest.kt
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
Labels: ready for review

#483 fix source missing when styles reloaded
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerTest.kt
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
Labels: location-layer-plugin, ready for review

#497 deprecate all methods in geojson plugin
  config/checkstyle/checkstyle.xml
  plugin-geojson/CHANGELOG.md
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/GeoJsonPlugin.java
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/GeoJsonPluginBuilder.java
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/listener/OnLoadingGeoJsonListener.java
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/listener/OnMarkerEventListener.java
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/model/DataModel.java
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/model/MarkerData.java
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/model/PolyData.java
Labels: ready for review

#480 Remove branch field which isn’t valid anymore inside CircleCI
  circle.yml
Labels: ready for review

#501 Release geojson 0.3.0
  plugin-cluster/gradle.properties
  plugin-geojson/CHANGELOG.md
  plugin-geojson/gradle.properties
Labels: geojson-plugin

#505 Release llp 0.5.2
  plugin-cluster/gradle.properties
  plugin-locationlayer/CHANGELOG.md
Labels: location-layer-plugin

#403 Remove and readd onMapChange in onStart/onStop
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/LocationLayerMapChangeActivity.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java
Labels: Location Layer Plugin, ready for review

#516 Sets initial value to infinity to prevent puck showing at nullisland
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
Labels: Location Layer Plugin, ready for review

#528 enable/disable inside lifecycle methods
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java
Labels: ready for review

#525 don’t update stale state if it’s not enabled in options
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/IsolatedActivityPluginTest.kt
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
Labels: ready for review

#520 Update LocationLayerPlugin permission annotations
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java
Labels: location-layer-plugin

#526 Fix accuracy circle color not being set correctly
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/IsolatedActivityPluginTest.kt
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
Labels: ready for review

#527 Adds constructor which doesn't take in a locationEngine
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/IsolatedActivityPluginTest.kt
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java
Labels: ready for review

#534 Deprecate all public methods in cluster plugin
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/MarkerManager.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/Cluster.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/ClusterItem.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/ClusterManagerPlugin.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/algo/Algorithm.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/algo/GridBasedAlgorithm.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/algo/PreCachingAlgorithmDecorator.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/algo/StaticCluster.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/view/ClusterRenderer.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/view/DefaultClusterRenderer.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/data/Geometry.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/data/Point.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/geometry/Bounds.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/geometry/Point.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/projection/SphericalMercatorProjection.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/quadtree/PointQuadTree.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/ui/BubbleDrawable.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/ui/IconGenerator.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/ui/RotationLayout.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/ui/SquareTextView.java
Labels: cluster-plugin, ready for review

#531 bumped map version
  gradle/dependencies.gradle
Labels: dependency-update
