Repository mapbox/mapbox-plugins-android, pull requests merged in 2018-03, with the labels that each got.

#327 Gestures logic for camera tracking, new telemetry library
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/FeatureOverviewActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/CompassListenerActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/LocationLayerMapChangeActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/LocationLayerModesActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/ManualLocationUpdatesActivity.java
  gradle/dependencies.gradle
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerCamera.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptions.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/OnCameraTrackingChangedListener.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/Utils.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/MapAnimator.java
  plugin-locationlayer/src/main/res/values/dimens.xml
  plugin-locationlayer/src/test/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptionsTest.java
Labels: location-layer-plugin

#330 Switched to sonarcloud
  circle.yml
  gradle/sonarqube.gradle
Labels: ready for review

#303 Basic readme setup for localization plugin
  README.md
  plugin-localization/README.md
Labels: documentation, ready for review

#334 added release automation
  .gitignore
  release/README.md
  release/__init__.py
  release/ci.py
  release/constants.py
  release/git.py
  release/javadoc.py
  release/menu.py
  release/release_final.py
  release/utils.py
  release/version.py
Labels: ready for review

#275 Resolve traffic plugin not showing
  app/build.gradle
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/TrafficActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/CompassListenerActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/LocationLayerMapChangeActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/LocationLayerModesActivity.java
  plugin-geojson/build.gradle
  plugin-traffic/build.gradle
  plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java
Labels: ready for review

#337 adds missing back button click action in place picker
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/picker/ui/PlacePickerActivity.java
  plugin-places/src/main/res/layout/mapbox_toolbar_place_picker.xml
Labels: ready for review

#339 added javadoc to the placeOptions class
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/model/PlaceOptions.java
Labels: ready for review

#338 Update checkstyle file
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerTest.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/CompassListenerActivity.java
  config/checkstyle/checkstyle.xml
  gradle/checkstyle.gradle
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/algo/NonHierarchicalDistanceBasedAlgorithm.java
  plugin-cluster/src/main/java/com/mapbox/mapboxsdk/plugins/cluster/clustering/algo/StaticCluster.java
Labels: ready for review

#348 release traffic 0.4.0
  plugin-traffic/CHANGELOG.md
  plugin-traffic/README.md
  plugin-traffic/gradle.properties
  release/javadoc.py
Labels: traffic-plugin

#340 Fixed jacoco test reporting
  app/build.gradle
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerTest.java
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/data/TestData.java
  build.gradle
  gradle/dependencies.gradle
  gradle/jacoco.gradle
  gradle/sonarqube.gradle
  plugin-building/build.gradle
  plugin-cluster/build.gradle
  plugin-geojson/build.gradle
  plugin-localization/build.gradle
  plugin-locationlayer/build.gradle
  plugin-offline/build.gradle
  plugin-places/build.gradle
  plugin-traffic/build.gradle
  plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java
Labels: ready for review

#329 Add Offline region selector UI
  app/build.gradle
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/data/SearchHistoryDaoTest.java
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/ui/PlaceAutocompleteFragmentTest.java
  app/src/debug/AndroidManifest.xml
  app/src/debug/java/com/mapbox/mapboxsdk/plugins/testapp/activity/SingleFragmentActivity.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/offline/OfflineUiComponentsActivity.java
  app/src/main/res/layout/activity_offline_download.xml
  app/src/main/res/layout/activity_offline_ui_components.xml
  app/src/main/res/values/strings.xml
  plugin-offline/build.gradle
  plugin-offline/src/main/AndroidManifest.xml
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/Constants.java
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/NotificationOptions.java
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/OfflineRegionSelector.java
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/ui/OfflineActivity.java
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/ui/RegionSelectedCallback.java
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/ui/RegionSelectionFragment.java
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/utils/ColorUtils.java
  plugin-offline/src/main/res/drawable/mapbox_ic_arrow_back.xml
  plugin-offline/src/main/res/drawable/mapbox_ic_check.xml
  plugin-offline/src/main/res/drawable/mapbox_region_selection_scrim.xml
  plugin-offline/src/main/res/layout/mapbox_offline_activity.xml
  plugin-offline/src/main/res/layout/mapbox_offline_region_selection_fragment.xml
  plugin-offline/src/main/res/layout/mapbox_offline_toolbar.xml
  plugin-offline/src/main/res/values/mapbox_colors.xml
  plugin-offline/src/main/res/values/mapbox_dimens.xml
  plugin-offline/src/main/res/values/mapbox_strings.xml
Labels: ready for review

#352 fixed folder structure in localization module
  plugin-localization/src/main/java/com/mapbox/mapboxsdk/plugins/localization/LocalizationPlugin.java
  plugin-localization/src/main/java/com/mapbox/mapboxsdk/plugins/localization/MapLocale.java
  plugin-localization/src/main/java/com/mapbox/mapboxsdk/plugins/localization/package-info.java
Labels: ready for review

#356 only set elevation if values greater than zero
  plugin-locationlayer/CHANGELOG.md
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
Labels: ready for review

#358 Disable leak canary when test are running
  app/build.gradle
Labels: ready for review

#342 Add some test
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/data/TestData.java
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/ui/PlaceAutocompleteFragmentTest.java
  plugin-places/build.gradle
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/data/converter/CarmenFeatureConverter.java
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/data/entity/SearchHistoryEntity.java
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/ui/PlaceAutocompleteFragment.java
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/common/PlaceConstants.java
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/picker/PlacePicker.java
  plugin-places/src/test/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/data/converter/CarmenFeatureConverterTest.java
  plugin-places/src/test/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/data/entity/SearchHistoryEntityTest.java
  plugin-places/src/test/java/com/mapbox/mapboxsdk/plugins/places/picker/PlacePickerTest.java
  plugin-places/src/test/java/com/mapbox/mapboxsdk/plugins/places/picker/model/PlacePickerOptionsTest.java
  plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java
Labels: ready for review

#377 Fix places offline issues
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/ui/PlaceAutocompleteFragmentTest.java
  app/src/debug/AndroidManifest.xml
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/ui/PlaceAutocompleteFragment.java
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/viewmodel/PlaceAutocompleteViewModel.java
  plugin-places/src/main/res/drawable/mapbox_ic_offline.xml
  plugin-places/src/main/res/layout/mapbox_fragment_autocomplete_card.xml
  plugin-places/src/main/res/layout/mapbox_fragment_autocomplete_full.xml
  plugin-places/src/main/res/layout/mapbox_item_offline_message.xml
  plugin-places/src/main/res/layout/mapbox_toolbar_place_picker.xml
  plugin-places/src/main/res/values/strings.xml
Labels: ready for review

#373 Add consumer proguard rules to all plugins
  app/build.gradle
  app/proguard-rules.pro
  circle.yml
  plugin-geojson/build.gradle
  plugin-geojson/proguard-consumer.pro
  plugin-locationlayer/build.gradle
  plugin-locationlayer/proguard-consumer.pro
  plugin-offline/build.gradle
  plugin-offline/proguard-consumer.pro
  plugin-places/build.gradle
  plugin-places/proguard-consumer.pro
Labels: ready for review

#384 update maps sdk to latest beta
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerTest.java
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPluginTest.java
  app/src/androidTest/java/com/mapbox/mapboxsdk/utils/OnMapReadyIdlingResource.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/BuildingActivity.java
  gradle/dependencies.gradle
  plugin-building/src/main/java/com/mapbox/mapboxsdk/plugins/building/BuildingPlugin.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerCamera.java
  plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java
Labels: building-plugin, location-layer-plugin, traffic-plugin

#388 Fix order of interpolator expression
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
Labels: bug, location-layer-plugin

#293 Map + Location Animators
  app/build.gradle
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerTest.java
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPluginTest.java
  app/src/androidTest/java/com/mapbox/mapboxsdk/utils/OnMapReadyIdlingResource.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/BuildingActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/FeatureOverviewActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/CompassListenerActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/LocationLayerMapChangeActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/LocationLayerModesActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/location/ManualLocationUpdatesActivity.java
  app/src/main/res/layout/activity_location_layer_mode.xml
  app/src/main/res/menu/menu_location.xml
  app/src/main/res/values/strings.xml
  gradle/dependencies.gradle
  plugin-building/src/main/java/com/mapbox/mapboxsdk/plugins/building/BuildingPlugin.java
  plugin-geojson/build.gradle
  plugin-geojson/src/main/java/com/mapbox/mapboxsdk/plugins/geojson/GeoJsonPlugin.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/CompassManager.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayer.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerCamera.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerConstants.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerMode.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptions.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/OnCameraTrackingChangedListener.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/OnLocationLayerClickListener.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/OnLocationLayerLongClickListener.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/OnLocationStaleListener.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/StaleStateManager.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/StaleStateRunnable.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/Utils.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/BearingAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/LatLngAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/MapAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/TiltAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/ZoomAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/modes/CameraMode.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/modes/RenderMode.java
  plugin-locationlayer/src/main/res/values/attrs.xml
  plugin-locationlayer/src/main/res/values/dimens.xml
  plugin-locationlayer/src/main/res/values/styles.xml
  plugin-locationlayer/src/test/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerOptionsTest.java
  plugin-offline/src/main/java/com/mapbox/mapboxsdk/plugins/offline/ui/RegionSelectionFragment.java
  plugin-traffic/src/main/java/com/mapbox/mapboxsdk/plugins/traffic/TrafficPlugin.java
Labels: location-layer-plugin

#393 Filter location updates and remove unused animator code
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/MapAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/TiltAnimator.java
  plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/camera/ZoomAnimator.java
Labels: location-layer-plugin
