Repository mapbox/mapbox-plugins-android, pull requests merged in 2019-07, with the labels that each got.

#1007 Refactored `fromUrl` usage to `fromUri`
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/BulkSymbolActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/DynamicSymbolChangeActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/FillChangeActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/LineChangeActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/annotation/PressForSymbolActivity.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/localization/LocalizationActivity.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/traffic/TrafficActivity.kt
Labels: enhancement, ready for review

#1010 Change the unit of scalebar according distance
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/scalebar/ScalebarActivity.kt
  plugin-scalebar/src/main/java/com/mapbox/pluginscalebar/ScaleBarConstants.java
  plugin-scalebar/src/main/java/com/mapbox/pluginscalebar/ScaleBarWidget.java
Labels: scale-plugin

#1012 Adding Kotlin lint check plugin and cleanup tweaks
  .editorconfig
  Makefile
  app/build.gradle
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/Utils.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/building/BuildingActivity.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/ktx/maps/MapboxKtxActivity.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/localization/LocalizationActivity.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/offline/OfflineDownloadActivity.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/offline/OfflineUiComponentsActivity.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/places/PickerLauncherActivity.kt
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/scalebar/ScalebarActivity.kt
  build.gradle
  gradle/dependencies.gradle
Labels: enhancement, ready for review

#999 Maps SDK 8.2.0
  gradle/dependencies.gradle
Labels: ready for review

#1022 Release ScalebarPlugin 0.2.0
  CHANGELOG.md
  plugin-scalebar/CHANGELOG.md
  plugin-scalebar/README.md
  plugin-scalebar/gradle.properties
Labels: scale-plugin

#1023 Added scalebar to plugin list at top of makefile
  Makefile
Labels: ready for review, scripting
