Repository mapbox/mapbox-plugins-android, pull requests merged in 2020-03, with the labels that each got.

#1086 Bumped Java SDK to 5.0.0
  gradle/dependencies.gradle
Labels: ready for review, ⚠️ DO NOT MERGE

#1099 Bumped Maps SDK to 9.0.0
  gradle/dependencies.gradle
Labels: ready for review

#1103 Release new versions of all plugins with v9 prefix
  README.md
  plugin-annotation/CHANGELOG.md
  plugin-annotation/README.md
  plugin-annotation/gradle.properties
  plugin-building/CHANGELOG.md
  plugin-building/README.md
  plugin-building/gradle.properties
  plugin-localization/CHANGELOG.md
  plugin-localization/README.md
  plugin-localization/gradle.properties
  plugin-markerview/CHANGELOG.md
  plugin-markerview/README.md
  plugin-markerview/gradle.properties
  plugin-offline/CHANGELOG.md
  plugin-offline/README.md
  plugin-offline/gradle.properties
  plugin-places/CHANGELOG.md
  plugin-places/README.md
  plugin-places/gradle.properties
  plugin-scalebar/CHANGELOG.md
  plugin-scalebar/README.md
  plugin-scalebar/gradle.properties
  plugin-traffic/CHANGELOG.md
  plugin-traffic/README.md
  plugin-traffic/gradle.properties
Labels: ready for review

#1048 Add option to config max width of scalebar.
  app/src/androidTest/java/com/mapbox/mapboxsdk/plugins/scalebar/ScaleBarTest.java
  app/src/main/java/com/mapbox/mapboxsdk/plugins/testapp/activity/scalebar/ScalebarActivity.kt
  plugin-scalebar/src/main/java/com/mapbox/pluginscalebar/ScaleBarOptions.java
  plugin-scalebar/src/main/java/com/mapbox/pluginscalebar/ScaleBarWidget.java
Labels: scale-plugin

#1107 [places] Setting reverse geocoding BottomSheetBehavior hideable to true
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/picker/ui/CurrentPlaceSelectionBottomSheet.java
Labels: bug, places-plugin, ready for review

#1110 Java SDK bump to 5.1.0
  gradle/dependencies.gradle
Labels: ready for review

#1112 Release Places 0.11.0 and Scalebar 0.5.0
  plugin-places/CHANGELOG.md
  plugin-places/README.md
  plugin-places/gradle.properties
  plugin-scalebar/CHANGELOG.md
  plugin-scalebar/README.md
  plugin-scalebar/gradle.properties
Labels: places-plugin, ready for review, scale-plugin
