Repository mapbox/mapbox-plugins-android, pull requests merged in 2020-04, with the labels that each got.

#1106 Include a new label (`confirmed`) that will be exempted by stalebot.
  .github/stale.yml
Labels: ready for review

#1113 Bumped Maps SDK to 9.1.0
  gradle/dependencies.gradle
Labels: ready for review

#1116 Added .baseUrl() to Places Plugin's PlaceOptions builder
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/model/PlaceOptions.java
  plugin-places/src/main/java/com/mapbox/mapboxsdk/plugins/places/autocomplete/viewmodel/PlaceAutocompleteViewModel.java
Labels: enhancement, places-plugin, ready for review

#1118 Release Places 0.12.0
  plugin-places/CHANGELOG.md
  plugin-places/README.md
  plugin-places/gradle.properties
Labels: places-plugin, ready for review

#1119 Removed stale bot settings for this repo
  .github/stale.yml
Labels: ready for review, scripting
